### ISSUE TITLE
sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by Chriszhangmw** [neuml/paperetl#45]
!python -m paperetl.file paperetl/file/data paperetl/models

get the following error:

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/anaconda/envs/azureml_py38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/paperetl/file/__main__.py", line 11, in <module>
    Execute.run(
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/paperetl/file/execute.py", line 176, in run
    db = Factory.create(url, replace)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/paperetl/factory.py", line 36, in create
    return SQLite(url.replace("sqlite://", ""), replace)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/paperetl/sqlite.py", line 104, in __init__
    self.create(SQLite.ARTICLES, "articles")
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/paperetl/sqlite.py", line 198, in create
    self.cur.execute(create)
sqlite3.OperationalError: database is locked

**Comment by Chriszhangmw** [comment]
after I kill the process related to sqlite, run again, but get another error:

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/anaconda/envs/azureml_py38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/paperetl/file/__main__.py", line 11, in <module>
    Execute.run(
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/paperetl/file/execute.py", line 176, in run
    db = Factory.create(url, replace)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/paperetl/factory.py", line 36, in create
    return SQLite(url.replace("sqlite://", ""), replace)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/paperetl/sqlite.py", line 113, in __init__
    self.sindex = int(self.cur.execute(SQLite.SECTION_COUNT).fetchone()[0]) + 1
sqlite3.OperationalError: no such table: sections

**Comment by Chriszhangmw** [comment]
does anybody can help that?

**Comment by davidmezzetti** [comment]
I would delete everything from `paperetl/models` and try again. The database locked error would only happen if another process was accessing it. I would make sure there isn't multiple instances of the paperetl process running.

**Comment by Chriszhangmw** [comment]
![image](https://user-images.githubusercontent.com/52879076/222037916-efdb999d-9a41-484b-b5d4-3f6a976a7f3e.png)

**Comment by Chriszhangmw** [comment]
![image](https://user-images.githubusercontent.com/52879076/222038236-42026302-bbbb-4166-a635-ca3e9e7fa83a.png)
the size is 0

**Comment by davidmezzetti** [comment]
Do you have data in paperetl/data? It seems like nothing was processed.

**Comment by davidmezzetti** [comment]
Closing this issue due to inactivity. Please re-open or open a new issue if there are further questions.
